# Generated by Django 5.0.1 on 2024-02-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=499)),
                ('option2', models.CharField(max_length=499)),
                ('option3', models.CharField(max_length=499)),
                ('option4', models.CharField(default='', max_length=499)),
                ('answer', models.CharField(max_length=499)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(default='', max_length=499)),
                ('generated_Date', models.DateTimeField(auto_now_add=True)),
                ('start_test_time', models.DateTimeField(blank=True, null=True)),
                ('submission_test_time', models.DateTimeField(blank=True, null=True)),
                ('test_score', models.CharField(blank=True, max_length=9, null=True)),
                ('user_submitted_answer', models.TextField(blank=True, null=True)),
                ('questions', models.ManyToManyField(blank=True, to='testgenerator.mcqmodel')),
            ],
        ),
    ]
